Bundles in Use
==============

What follows is a list of the bundles in use in my vim configuration and the
reason they're in there, in an attempt to make sure I remember why they're
there in the future.


ack.vim ::
	For ':Ack', since I use ack rather heavily. Configured to use ag for
	performance reasons.

asciidoc-vim ::
	AsciiDoc syntax highlighting.

ctrlp.vim ::
	Slightly faster buffer, file, tag, etc. lookup using ',t', ',T', and
	',r' (buffers, files, and tags respectively).

delimitMate ::
	Auto-closing brackets and quotes. (Type a quote, get a second inserted
	after the cursor.)

gundo.vim ::
	Better undo tree navigation. Not used often, but I've pulled it out
	often enough that I haven't axed it.

lightline ::
	Pretty status line. Also pretty useful. Replaces vim-airline, which was
	trying to do too much most of the time and ended up with a cluttered
	status line as a result.

Smart-Tabs ::
	Indenting with tabs and aligning with spaces. Guarantees everyone can
	use their own indent sizes without messing up mid-line alignments, such
	as for comments, assignments, and so on.

syntastic ::
	Syntax checking.

tabular ::
	Alignments (e.g., align comments, assignments, etc.).

tagbar ::
	Code overview using tags. Mainly here for status line usage, actually.

ultisnips ::
	Snippets. Works better than neosnippet.

unite-help ::
	':help' search using Unite.

unite.vim ::
	Somewhat useful tool for searching things. The fuzzy matching is a
	little iffy and CtrlP generally works better for opening files. It's
	very useful for grep/ack-ing though (bound to '<Space>kf' right now).

vim-bbye ::
	Buffer deletion that does what I want. Provides ':Bdelete', which I
	have mapped to ',q'.

vim-buftabline ::
	Displays buffer names / names in the tabline. Basically accomplishes
	what I wanted with bufferline, but without tabs.

vim-commentary ::
	Commenting mappings. Replaces nerdcomments because it doesn't have
	really weird mappings.

vim-easymotion ::
	Jumping around buffers.

vim-fugitive ::
	Git support, mainly used for Gdiff so I can visually put hunks in the
	index, though it's useful overall.

vim-gitgutter ::
	Seeing which lines in a source file have changed. Would have a similar
	plugin for Mercurial, but Mercurial integration in everything is slow
	and I've given up on this.

vim-go ::
	Go support (syntax, completion, etc.)

vim-multiple-cursors ::
	Multiple caret support. Admittedly not using it all that much and it's
	pretty clunky, but I want to give it a shot for when I have time to
	work out what exactly it can do.

vim-peekaboo ::
	Displays a popup on the right side showing the contents of some
	registers when using them. Fairly useful, but I've had surprisingly
	little luck with it for macros so far. Still have to do ':reg' for
	those, it seems, otherwise I have trouble finding them at times.

vim-sleuth ::
	Indentation detection. Likely to be removed for sheer annoyance factor
	when it un-sets 'shiftwidth'.

vim-surround ::
	Surrounding stuff with stuff, changing/adding/removing
	braces/quotes/other things.

vim-unimpaired ::
	Mainly using this for transposing lines (i.e., with '[e' and ']e'), but
	it has a lot of other tools I use sporadically.

vim-vinegar ::
	Replaces nerdtree (sort of) since netrw doesn't pop up on the side.
	Since hidden is set, there's no unnecessary splitting and messing-up-of
	my window layout.

vimproc.vim ::
	Purportedly for other plugins to do asynchronous stuff. Only have it
	here as a requirement of neocomplete. Pretty sure it's unused by
	neosnippet, but I haven't looked into what else is using it yet.

xterm-color-table.vim ::
	Xterm color table. Useful for when I need to tweak triplejelly.

YankRing.vim ::
	For keeping yank/paste history in a more useful place than registers.
	Heavily used more for the ability to mash 'p' or 'P' and hit '<C-p>' and
	'<C-n>' to move through previous entries in the ring and occasionally
	',p' for pasting.

// vim: set syntax=asciidoc ts=8 tw=79 sw=8 noexpandtab:
